import { type Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { PropsWithChildren } from 'react';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Order tracking',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <div
            className="container mx-auto h-screen"
            style={{ maxWidth: '640px' }}
          >
            <div className="pt-8 md:pt-16 h-full">
              <div className="py-4 px-10 h-full bg-white rounded-t-md">
                {children}
              </div>
            </div>
          </div>
      </body>
    </html>
  );
}
