import { type Metadata } from 'next';
import { PropsWithChildren } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Order tracking',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div style={{ maxWidth: '640px', margin: '100px auto 0' }}>
          <div style={{ padding: '0 10px' }}>{children}</div>
        </div>
      </body>
    </html>
  );
}
